//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eFormAPI.Web.Resources {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("eFormAPI.Web.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AdminUserNotFound {
            get {
                return ResourceManager.GetString("AdminUserNotFound", resourceCulture);
            }
        }

        public static string CannotOpenDatabes {
            get {
                return ResourceManager.GetString("CannotOpenDatabes", resourceCulture);
            }
        }

        public static string CantDeletePrimaryAdminUser {
            get {
                return ResourceManager.GetString("CantDeletePrimaryAdminUser", resourceCulture);
            }
        }

        public static string CantObtainSettingsFromWebConfig {
            get {
                return ResourceManager.GetString("CantObtainSettingsFromWebConfig", resourceCulture);
            }
        }

        public static string CantUpdateSettingsInWebConfig {
            get {
                return ResourceManager.GetString("CantUpdateSettingsInWebConfig", resourceCulture);
            }
        }

        public static string CaseCouldNotBeRemoved {
            get {
                return ResourceManager.GetString("CaseCouldNotBeRemoved", resourceCulture);
            }
        }

        public static string CaseCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("CaseCouldNotBeUpdated", resourceCulture);
            }
        }

        public static string CaseHasBeenUpdated {
            get {
                return ResourceManager.GetString("CaseHasBeenUpdated", resourceCulture);
            }
        }

        public static string CaseLoadingFailed {
            get {
                return ResourceManager.GetString("CaseLoadingFailed", resourceCulture);
            }
        }

        public static string CaseParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("CaseParamDeletedSuccessfully", resourceCulture);
            }
        }

        public static string CheckConnectionString {
            get {
                return ResourceManager.GetString("CheckConnectionString", resourceCulture);
            }
        }

        public static string CheckSettingsBeforeProceed {
            get {
                return ResourceManager.GetString("CheckSettingsBeforeProceed", resourceCulture);
            }
        }

        public static string ColumnsWereUpdated {
            get {
                return ResourceManager.GetString("ColumnsWereUpdated", resourceCulture);
            }
        }

        public static string ConnectionStringAlreadyExist {
            get {
                return ResourceManager.GetString("ConnectionStringAlreadyExist", resourceCulture);
            }
        }

        public static string CoreIsNotStarted {
            get {
                return ResourceManager.GetString("CoreIsNotStarted", resourceCulture);
            }
        }

        public static string CouldNotWriteConnectionString {
            get {
                return ResourceManager.GetString("CouldNotWriteConnectionString", resourceCulture);
            }
        }

        public static string DeviceUserCouldNotBeCreated {
            get {
                return ResourceManager.GetString("DeviceUserCouldNotBeCreated", resourceCulture);
            }
        }

        public static string DeviceUserCouldNotBeObtained {
            get {
                return ResourceManager.GetString("DeviceUserCouldNotBeObtained", resourceCulture);
            }
        }

        public static string DeviceUserCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("DeviceUserCouldNotBeUpdated", resourceCulture);
            }
        }

        public static string DeviceUserNotFound {
            get {
                return ResourceManager.GetString("DeviceUserNotFound", resourceCulture);
            }
        }

        public static string DeviceUserPa {
            get {
                return ResourceManager.GetString("DeviceUserPa", resourceCulture);
            }
        }

        public static string DeviceUserParamCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("DeviceUserParamCouldNotBeDeleted", resourceCulture);
            }
        }

        public static string DeviceUserParamCouldNotBeEdited {
            get {
                return ResourceManager.GetString("DeviceUserParamCouldNotBeEdited", resourceCulture);
            }
        }

        public static string DeviceUserParamCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("DeviceUserParamCouldNotBeUpdated", resourceCulture);
            }
        }

        public static string DeviceUserParamCreatedSuccessfully {
            get {
                return ResourceManager.GetString("DeviceUserParamCreatedSuccessfully", resourceCulture);
            }
        }

        public static string DeviceUserParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeviceUserParamDeletedSuccessfully", resourceCulture);
            }
        }

        public static string DeviceUserUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("DeviceUserUpdatedSuccessfully", resourceCulture);
            }
        }

        public static string eFormCouldNotBeCreated {
            get {
                return ResourceManager.GetString("eFormCouldNotBeCreated", resourceCulture);
            }
        }

        public static string eFormParamCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("eFormParamCouldNotBeDeleted", resourceCulture);
            }
        }

        public static string eFormParamCreatedSuccessfully {
            get {
                return ResourceManager.GetString("eFormParamCreatedSuccessfully", resourceCulture);
            }
        }

        public static string eFormParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("eFormParamDeletedSuccessfully", resourceCulture);
            }
        }

        public static string ErrorWhenDeletingSearchableList {
            get {
                return ResourceManager.GetString("ErrorWhenDeletingSearchableList", resourceCulture);
            }
        }

        public static string ErrorWhenObtainingSearchableList {
            get {
                return ResourceManager.GetString("ErrorWhenObtainingSearchableList", resourceCulture);
            }
        }

        public static string ErrorWhileAddNewPassword {
            get {
                return ResourceManager.GetString("ErrorWhileAddNewPassword", resourceCulture);
            }
        }

        public static string ErrorWhileCreatingFileForSDK {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingFileForSDK", resourceCulture);
            }
        }

        public static string ErrorWhileCreatingParamTag {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingParamTag", resourceCulture);
            }
        }

        public static string ErrorWhileCreatingUser {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingUser", resourceCulture);
            }
        }

        public static string ErrorWhileCreatingWorker {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingWorker", resourceCulture);
            }
        }

        public static string ErrorWhileDeletingSelectableList {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingSelectableList", resourceCulture);
            }
        }

        public static string ErrorWhileDeletingTag {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingTag", resourceCulture);
            }
        }

        public static string ErrorWhileDeletingUser {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingUser", resourceCulture);
            }
        }

        public static string ErrorWhileObtainColumns {
            get {
                return ResourceManager.GetString("ErrorWhileObtainColumns", resourceCulture);
            }
        }

        public static string ErrorWhileObtainSelectableList {
            get {
                return ResourceManager.GetString("ErrorWhileObtainSelectableList", resourceCulture);
            }
        }

        public static string ErrorWhileObtainTags {
            get {
                return ResourceManager.GetString("ErrorWhileObtainTags", resourceCulture);
            }
        }

        public static string ErrorWhileObtainUsers {
            get {
                return ResourceManager.GetString("ErrorWhileObtainUsers", resourceCulture);
            }
        }

        public static string ErrorWhileRemovingOldPassword {
            get {
                return ResourceManager.GetString("ErrorWhileRemovingOldPassword", resourceCulture);
            }
        }

        public static string ErrorWhileRotateImage {
            get {
                return ResourceManager.GetString("ErrorWhileRotateImage", resourceCulture);
            }
        }

        public static string ErrorWhileUpdatingColumns {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingColumns", resourceCulture);
            }
        }

        public static string ErrorWhileUpdatingPSK {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingPSK", resourceCulture);
            }
        }

        public static string ErrorWhileUpdatingTemplateTags {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingTemplateTags", resourceCulture);
            }
        }

        public static string ErrorWhileUpdatingUser {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingUser", resourceCulture);
            }
        }

        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }

        public static string FolderError {
            get {
                return ResourceManager.GetString("FolderError", resourceCulture);
            }
        }

        public static string ImageDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ImageDeletedSuccessfully", resourceCulture);
            }
        }

        public static string ImageNotDeleted {
            get {
                return ResourceManager.GetString("ImageNotDeleted", resourceCulture);
            }
        }

        public static string ImageRotatedSuccessfully {
            get {
                return ResourceManager.GetString("ImageRotatedSuccessfully", resourceCulture);
            }
        }

        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }

        public static string InvalidSecurityCode {
            get {
                return ResourceManager.GetString("InvalidSecurityCode", resourceCulture);
            }
        }

        public static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }

        public static string MainConnectionStringIsInvalid {
            get {
                return ResourceManager.GetString("MainConnectionStringIsInvalid", resourceCulture);
            }
        }

        public static string NewOTPCreatedSuccessfully {
            get {
                return ResourceManager.GetString("NewOTPCreatedSuccessfully", resourceCulture);
            }
        }

        public static string ParamCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ParamCreatedSuccessfully", resourceCulture);
            }
        }

        public static string ParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ParamDeletedSuccessfully", resourceCulture);
            }
        }

        public static string ParamPairedSuccessfully {
            get {
                return ResourceManager.GetString("ParamPairedSuccessfully", resourceCulture);
            }
        }

        public static string ParamUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ParamUpdatedSuccessfully", resourceCulture);
            }
        }

        public static string PleaseSetupSecurityCode {
            get {
                return ResourceManager.GetString("PleaseSetupSecurityCode", resourceCulture);
            }
        }

        public static string RequestFieldsAreNotFilled {
            get {
                return ResourceManager.GetString("RequestFieldsAreNotFilled", resourceCulture);
            }
        }

        public static string RoleIsRequired {
            get {
                return ResourceManager.GetString("RoleIsRequired", resourceCulture);
            }
        }

        public static string SDKConnectionStringIsInvalid {
            get {
                return ResourceManager.GetString("SDKConnectionStringIsInvalid", resourceCulture);
            }
        }

        public static string SearchableListCreationFailed {
            get {
                return ResourceManager.GetString("SearchableListCreationFailed", resourceCulture);
            }
        }

        public static string SearchableListLoadingFailed {
            get {
                return ResourceManager.GetString("SearchableListLoadingFailed", resourceCulture);
            }
        }

        public static string SelectableGroupLoadingFailed {
            get {
                return ResourceManager.GetString("SelectableGroupLoadingFailed", resourceCulture);
            }
        }

        public static string SelectableListCreationFailed {
            get {
                return ResourceManager.GetString("SelectableListCreationFailed", resourceCulture);
            }
        }

        public static string SettingsUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsUpdatedSuccessfully", resourceCulture);
            }
        }

        public static string SiteParamCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("SiteParamCouldNotBeDeleted", resourceCulture);
            }
        }

        public static string SiteParamCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("SiteParamCouldNotBeUpdated", resourceCulture);
            }
        }

        public static string SiteParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("SiteParamDeletedSuccessfully", resourceCulture);
            }
        }

        public static string SiteParamNotFound {
            get {
                return ResourceManager.GetString("SiteParamNotFound", resourceCulture);
            }
        }

        public static string SiteWithIdCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("SiteWithIdCouldNotBeDeleted", resourceCulture);
            }
        }

        public static string TagDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TagDeletedSuccessfully", resourceCulture);
            }
        }

        public static string TagParamCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TagParamCreatedSuccessfully", resourceCulture);
            }
        }

        public static string TemplateTagUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TemplateTagUpdatedSuccessfully", resourceCulture);
            }
        }

        public static string UnitParamOTPCouldNotCompleted {
            get {
                return ResourceManager.GetString("UnitParamOTPCouldNotCompleted", resourceCulture);
            }
        }

        public static string UnitWasSuccessfullyCreated {
            get {
                return ResourceManager.GetString("UnitWasSuccessfullyCreated", resourceCulture);
            }
        }

        public static string ErrorWhileCreatingUnit {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingUnit", resourceCulture);
            }
        }

        public static string UserNameOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("UserNameOrPasswordIncorrect", resourceCulture);
            }
        }

        public static string UserNotFoundUserName {
            get {
                return ResourceManager.GetString("UserNotFoundUserName", resourceCulture);
            }
        }

        public static string UserParamWasDeleted {
            get {
                return ResourceManager.GetString("UserParamWasDeleted", resourceCulture);
            }
        }

        public static string UserUserNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserUserNameAlreadyExist", resourceCulture);
            }
        }

        public static string UserUserNameWasCreated {
            get {
                return ResourceManager.GetString("UserUserNameWasCreated", resourceCulture);
            }
        }

        public static string UserUserNameWasUpdated {
            get {
                return ResourceManager.GetString("UserUserNameWasUpdated", resourceCulture);
            }
        }

        public static string WorkerParamCantBeDeleted {
            get {
                return ResourceManager.GetString("WorkerParamCantBeDeleted", resourceCulture);
            }
        }

        public static string WorkerParamCantBeUpdated {
            get {
                return ResourceManager.GetString("WorkerParamCantBeUpdated", resourceCulture);
            }
        }

        public static string WorkerParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("WorkerParamDeletedSuccessfully", resourceCulture);
            }
        }

        public static string WorkerParamWasUpdated {
            get {
                return ResourceManager.GetString("WorkerParamWasUpdated", resourceCulture);
            }
        }

        public static string WorkerWasSuccessfullyCreated {
            get {
                return ResourceManager.GetString("WorkerWasSuccessfullyCreated", resourceCulture);
            }
        }

        public static string YouNeedToBuyMoreLicenses {
            get {
                return ResourceManager.GetString("YouNeedToBuyMoreLicenses", resourceCulture);
            }
        }

        public static string YourEmailPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("YourEmailPasswordHasBeenReset", resourceCulture);
            }
        }

        public static string SecurityGroupNotFound {
            get {
                return ResourceManager.GetString("SecurityGroupNotFound", resourceCulture);
            }
        }

        public static string YouCantViewChangeOrDeleteAdmin {
            get {
                return ResourceManager.GetString("YouCantViewChangeOrDeleteAdmin", resourceCulture);
            }
        }

        public static string ErrorWhileObtainingPermissions {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingPermissions", resourceCulture);
            }
        }

        public static string ErrorWhileUpdatingPermissions {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingPermissions", resourceCulture);
            }
        }

        public static string PermissionsUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PermissionsUpdatedSuccessfully", resourceCulture);
            }
        }

        public static string ConnectionStringDoesNotExist {
            get {
                return ResourceManager.GetString("ConnectionStringDoesNotExist", resourceCulture);
            }
        }

        public static string eFormAlreadyInGroup {
            get {
                return ResourceManager.GetString("eFormAlreadyInGroup", resourceCulture);
            }
        }

        public static string eFormHasBeenDeletedFromGroup {
            get {
                return ResourceManager.GetString("eFormHasBeenDeletedFromGroup", resourceCulture);
            }
        }

        public static string eFormNotFound {
            get {
                return ResourceManager.GetString("eFormNotFound", resourceCulture);
            }
        }

        public static string ErrorWhileBindingEformToGroup {
            get {
                return ResourceManager.GetString("ErrorWhileBindingEformToGroup", resourceCulture);
            }
        }

        public static string ErrorWhileCreatingSecurityGroup {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingSecurityGroup", resourceCulture);
            }
        }

        public static string ErrorWhileDeletingEformFromGroup {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingEformFromGroup", resourceCulture);
            }
        }

        public static string ErrorWhileDeletingSecurityGroup {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingSecurityGroup", resourceCulture);
            }
        }

        public static string ErrorWhileObtainingAvailableEForms {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingAvailableEForms", resourceCulture);
            }
        }

        public static string ErrorWhileObtainingEformInfo {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingEformInfo", resourceCulture);
            }
        }

        public static string ErrorWhileObtainingSecurityGroup {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingSecurityGroup", resourceCulture);
            }
        }

        public static string ErrorWhileObtainingSecurityGroups {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingSecurityGroups", resourceCulture);
            }
        }

        public static string ErrorWhileObtainingUserMenu {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingUserMenu", resourceCulture);
            }
        }

        public static string ErrorWhileUpdatingSecurityGroup {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingSecurityGroup", resourceCulture);
            }
        }

        public static string PermissionForEformHasBeenUpdated {
            get {
                return ResourceManager.GetString("PermissionForEformHasBeenUpdated", resourceCulture);
            }
        }

        public static string SecurityGroupCreatedSuccessfully {
            get {
                return ResourceManager.GetString("SecurityGroupCreatedSuccessfully", resourceCulture);
            }
        }

        public static string SecurityGroupNameIsEmpty {
            get {
                return ResourceManager.GetString("SecurityGroupNameIsEmpty", resourceCulture);
            }
        }

        public static string SecurityGroupRemovedSuccessfully {
            get {
                return ResourceManager.GetString("SecurityGroupRemovedSuccessfully", resourceCulture);
            }
        }

        public static string SecurityGroupUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("SecurityGroupUpdatedSuccessfully", resourceCulture);
            }
        }

        public static string ErrorWhileObtainingSavedTags {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingSavedTags", resourceCulture);
            }
        }

        public static string ErrorWhileRemovingSavedTags {
            get {
                return ResourceManager.GetString("ErrorWhileRemovingSavedTags", resourceCulture);
            }
        }

        public static string ErrorWhileSavingTag {
            get {
                return ResourceManager.GetString("ErrorWhileSavingTag", resourceCulture);
            }
        }

        public static string InvalidTagId {
            get {
                return ResourceManager.GetString("InvalidTagId", resourceCulture);
            }
        }

        public static string InvalidTagName {
            get {
                return ResourceManager.GetString("InvalidTagName", resourceCulture);
            }
        }

        public static string SavedTagNotFound {
            get {
                return ResourceManager.GetString("SavedTagNotFound", resourceCulture);
            }
        }

        public static string TagAlreadySaved {
            get {
                return ResourceManager.GetString("TagAlreadySaved", resourceCulture);
            }
        }

        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }

        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }

        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }

        public static string DeviceUsers {
            get {
                return ResourceManager.GetString("DeviceUsers", resourceCulture);
            }
        }

        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }

        public static string MyEforms {
            get {
                return ResourceManager.GetString("MyEforms", resourceCulture);
            }
        }

        public static string SearchableList {
            get {
                return ResourceManager.GetString("SearchableList", resourceCulture);
            }
        }

        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }

        public static string SelectableList {
            get {
                return ResourceManager.GetString("SelectableList", resourceCulture);
            }
        }

        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        public static string Sites {
            get {
                return ResourceManager.GetString("Sites", resourceCulture);
            }
        }

        public static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }

        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }

        public static string Workers {
            get {
                return ResourceManager.GetString("Workers", resourceCulture);
            }
        }

        public static string PluginsSettings {
            get {
                return ResourceManager.GetString("PluginsSettings", resourceCulture);
            }
        }

        public static string EformReportNotFound {
            get {
                return ResourceManager.GetString("EformReportNotFound", resourceCulture);
            }
        }

        public static string ElementListNotProvided {
            get {
                return ResourceManager.GetString("ElementListNotProvided", resourceCulture);
            }
        }

        public static string ErrorWhileObtainingReportInfo {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingReportInfo", resourceCulture);
            }
        }

        public static string ErrorWhileUpdatingReport {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingReport", resourceCulture);
            }
        }

        public static string ReportUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ReportUpdatedSuccessfully", resourceCulture);
            }
        }

        public static string TemplateNotFound {
            get {
                return ResourceManager.GetString("TemplateNotFound", resourceCulture);
            }
        }

        public static string ErrorWhileObtainingPlugins {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingPlugins", resourceCulture);
            }
        }

        public static string ErrorWhileUpdatingPluginSettings {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingPluginSettings", resourceCulture);
            }
        }

        public static string PluginNotFound {
            get {
                return ResourceManager.GetString("PluginNotFound", resourceCulture);
            }
        }

        public static string CantEditPrimaryAdminUser {
            get {
                return ResourceManager.GetString("CantEditPrimaryAdminUser", resourceCulture);
            }
        }

        public static string CantUpdateRoleForPrimaryAdminUser {
            get {
                return ResourceManager.GetString("CantUpdateRoleForPrimaryAdminUser", resourceCulture);
            }
        }

        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }

        public static string ErrorWhileExecutingPluginInstall {
            get {
                return ResourceManager.GetString("ErrorWhileExecutingPluginInstall", resourceCulture);
            }
        }

        public static string ErrorWhileObtainingPluginList {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingPluginList", resourceCulture);
            }
        }

        public static string ErrorWhileObtainingSites {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingSites", resourceCulture);
            }
        }

        public static string ErrorWhileUpdatingTags {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingTags", resourceCulture);
            }
        }

        public static string TagNotFound {
            get {
                return ResourceManager.GetString("TagNotFound", resourceCulture);
            }
        }

        public static string TagUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TagUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}