{{- if .Values.ingress.enabled -}}
{{- $fullName := include "angularfrontend.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: customers
  labels:
    {{- include "angularfrontend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    external-dns.alpha.kubernetes.io/hostname: {{ regexReplaceAll "frontend-([1-9]+).*" $fullName "$1"}}.microting.com
    external-dns.alpha.kubernetes.io/ttl: "120" #optional
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        - "{{ regexReplaceAll "frontend-([1-9]+).*" $fullName "$1"}}.microting.com"
      secretName: "{{ regexReplaceAll "frontend-([1-9]+).*" $fullName "$1"}}.microting.com"
    {{- end }}
  {{- end }}
  defaultBackend:
    service:
      name: {{ $fullName }}
      port:
        number: {{ $svcPort }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ regexReplaceAll "frontend-([1-9]+).*" $fullName "$1"}}.microting.com
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
