//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EformBase.Pn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EformBase.Pn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin user not found.
        /// </summary>
        internal static string AdminUserNotFound {
            get {
                return ResourceManager.GetString("AdminUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t open database.
        /// </summary>
        internal static string CannotOpenDatabes {
            get {
                return ResourceManager.GetString("CannotOpenDatabes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete primary admin user.
        /// </summary>
        internal static string CantDeletePrimaryAdminUser {
            get {
                return ResourceManager.GetString("CantDeletePrimaryAdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t obtain settings from web.config.
        /// </summary>
        internal static string CantObtainSettingsFromWebConfig {
            get {
                return ResourceManager.GetString("CantObtainSettingsFromWebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t update settings in web.config.
        /// </summary>
        internal static string CantUpdateSettingsInWebConfig {
            get {
                return ResourceManager.GetString("CantUpdateSettingsInWebConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case could not be removed.
        /// </summary>
        internal static string CaseCouldNotBeRemoved {
            get {
                return ResourceManager.GetString("CaseCouldNotBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case could not be updated.
        /// </summary>
        internal static string CaseCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("CaseCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case has been updated.
        /// </summary>
        internal static string CaseHasBeenUpdated {
            get {
                return ResourceManager.GetString("CaseHasBeenUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case loading failed.
        /// </summary>
        internal static string CaseLoadingFailed {
            get {
                return ResourceManager.GetString("CaseLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case #{0} deleted successfully.
        /// </summary>
        internal static string CaseParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("CaseParamDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check connection string.
        /// </summary>
        internal static string CheckConnectionString {
            get {
                return ResourceManager.GetString("CheckConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check settings before proceed.
        /// </summary>
        internal static string CheckSettingsBeforeProceed {
            get {
                return ResourceManager.GetString("CheckSettingsBeforeProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns were updated.
        /// </summary>
        internal static string ColumnsWereUpdated {
            get {
                return ResourceManager.GetString("ColumnsWereUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string already exist.
        /// </summary>
        internal static string ConnectionStringAlreadyExist {
            get {
                return ResourceManager.GetString("ConnectionStringAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core is not started.
        /// </summary>
        internal static string CoreIsNotStarted {
            get {
                return ResourceManager.GetString("CoreIsNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write connection string in /bin/Input.txt.
        /// </summary>
        internal static string CouldNotWriteConnectionString {
            get {
                return ResourceManager.GetString("CouldNotWriteConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device User could not be created.
        /// </summary>
        internal static string DeviceUserCouldNotBeCreated {
            get {
                return ResourceManager.GetString("DeviceUserCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device User with such UId could not be obtained.
        /// </summary>
        internal static string DeviceUserCouldNotBeObtained {
            get {
                return ResourceManager.GetString("DeviceUserCouldNotBeObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device User could not be updated.
        /// </summary>
        internal static string DeviceUserCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("DeviceUserCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device User UId not found.
        /// </summary>
        internal static string DeviceUserNotFound {
            get {
                return ResourceManager.GetString("DeviceUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device User with id  &quot;{0}&quot; could not be deleted.
        /// </summary>
        internal static string DeviceUserPa {
            get {
                return ResourceManager.GetString("DeviceUserPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device User &quot;{0}&quot; could not be deleted.
        /// </summary>
        internal static string DeviceUserParamCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("DeviceUserParamCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device User with id {0} could not be edited.
        /// </summary>
        internal static string DeviceUserParamCouldNotBeEdited {
            get {
                return ResourceManager.GetString("DeviceUserParamCouldNotBeEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device User with id {0} could not be updated.
        /// </summary>
        internal static string DeviceUserParamCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("DeviceUserParamCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device user &quot;{0}&quot; created successfully.
        /// </summary>
        internal static string DeviceUserParamCreatedSuccessfully {
            get {
                return ResourceManager.GetString("DeviceUserParamCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device User &quot;{0}&quot; deleted successfully.
        /// </summary>
        internal static string DeviceUserParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeviceUserParamDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device User updated successfully.
        /// </summary>
        internal static string DeviceUserUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("DeviceUserUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eForm could not be created.
        /// </summary>
        internal static string eFormCouldNotBeCreated {
            get {
                return ResourceManager.GetString("eFormCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eForm &quot;{0}&quot; could not be deleted.
        /// </summary>
        internal static string eFormParamCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("eFormParamCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eForm &quot;{0}&quot; created successfully.
        /// </summary>
        internal static string eFormParamCreatedSuccessfully {
            get {
                return ResourceManager.GetString("eFormParamCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eForm &quot;{0}&quot; deleted successfully.
        /// </summary>
        internal static string eFormParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("eFormParamDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when deleting searchable list.
        /// </summary>
        internal static string ErrorWhenDeletingSearchableList {
            get {
                return ResourceManager.GetString("ErrorWhenDeletingSearchableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when obtaining searchable list.
        /// </summary>
        internal static string ErrorWhenObtainingSearchableList {
            get {
                return ResourceManager.GetString("ErrorWhenObtainingSearchableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while add new password.
        /// </summary>
        internal static string ErrorWhileAddNewPassword {
            get {
                return ResourceManager.GetString("ErrorWhileAddNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating file for SDK.
        /// </summary>
        internal static string ErrorWhileCreatingFileForSDK {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingFileForSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating &quot;{0}&quot; tag.
        /// </summary>
        internal static string ErrorWhileCreatingParamTag {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingParamTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when creating user.
        /// </summary>
        internal static string ErrorWhileCreatingUser {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating worker.
        /// </summary>
        internal static string ErrorWhileCreatingWorker {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when deleting selectable list.
        /// </summary>
        internal static string ErrorWhileDeletingSelectableList {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingSelectableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting tag.
        /// </summary>
        internal static string ErrorWhileDeletingTag {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting user.
        /// </summary>
        internal static string ErrorWhileDeletingUser {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while obtain columns.
        /// </summary>
        internal static string ErrorWhileObtainColumns {
            get {
                return ResourceManager.GetString("ErrorWhileObtainColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when obtaining selectable list.
        /// </summary>
        internal static string ErrorWhileObtainSelectableList {
            get {
                return ResourceManager.GetString("ErrorWhileObtainSelectableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while obtain tags.
        /// </summary>
        internal static string ErrorWhileObtainTags {
            get {
                return ResourceManager.GetString("ErrorWhileObtainTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when obtaining users.
        /// </summary>
        internal static string ErrorWhileObtainUsers {
            get {
                return ResourceManager.GetString("ErrorWhileObtainUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while removing old password.
        /// </summary>
        internal static string ErrorWhileRemovingOldPassword {
            get {
                return ResourceManager.GetString("ErrorWhileRemovingOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while rotate image.
        /// </summary>
        internal static string ErrorWhileRotateImage {
            get {
                return ResourceManager.GetString("ErrorWhileRotateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating columns.
        /// </summary>
        internal static string ErrorWhileUpdatingColumns {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating user PSK.
        /// </summary>
        internal static string ErrorWhileUpdatingPSK {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingPSK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating template tags.
        /// </summary>
        internal static string ErrorWhileUpdatingTemplateTags {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingTemplateTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when updating user.
        /// </summary>
        internal static string ErrorWhileUpdatingUser {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder error.
        /// </summary>
        internal static string FolderError {
            get {
                return ResourceManager.GetString("FolderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image deleted successfully.
        /// </summary>
        internal static string ImageDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ImageDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image was not deleted.
        /// </summary>
        internal static string ImageNotDeleted {
            get {
                return ResourceManager.GetString("ImageNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image rotated successfully.
        /// </summary>
        internal static string ImageRotatedSuccessfully {
            get {
                return ResourceManager.GetString("ImageRotatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Request.
        /// </summary>
        internal static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid security code.
        /// </summary>
        internal static string InvalidSecurityCode {
            get {
                return ResourceManager.GetString("InvalidSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string InvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main connection string is invalid.
        /// </summary>
        internal static string MainConnectionStringIsInvalid {
            get {
                return ResourceManager.GetString("MainConnectionStringIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New OTP created successfully.
        /// </summary>
        internal static string NewOTPCreatedSuccessfully {
            get {
                return ResourceManager.GetString("NewOTPCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} created successfully.
        /// </summary>
        internal static string ParamCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ParamCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deleted successfully.
        /// </summary>
        internal static string ParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("ParamDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; paired successfully.
        /// </summary>
        internal static string ParamPairedSuccessfully {
            get {
                return ResourceManager.GetString("ParamPairedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} updated successfully.
        /// </summary>
        internal static string ParamUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("ParamUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please setup security code on server.
        /// </summary>
        internal static string PleaseSetupSecurityCode {
            get {
                return ResourceManager.GetString("PleaseSetupSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required fields are not filled.
        /// </summary>
        internal static string RequestFieldsAreNotFilled {
            get {
                return ResourceManager.GetString("RequestFieldsAreNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role is required.
        /// </summary>
        internal static string RoleIsRequired {
            get {
                return ResourceManager.GetString("RoleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK connection string is invalid.
        /// </summary>
        internal static string SDKConnectionStringIsInvalid {
            get {
                return ResourceManager.GetString("SDKConnectionStringIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchable list creation failed.
        /// </summary>
        internal static string SearchableListCreationFailed {
            get {
                return ResourceManager.GetString("SearchableListCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searchable list loading failed.
        /// </summary>
        internal static string SearchableListLoadingFailed {
            get {
                return ResourceManager.GetString("SearchableListLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectable group loading failed.
        /// </summary>
        internal static string SelectableGroupLoadingFailed {
            get {
                return ResourceManager.GetString("SelectableGroupLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selectable list creation failed.
        /// </summary>
        internal static string SelectableListCreationFailed {
            get {
                return ResourceManager.GetString("SelectableListCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings updated successfully.
        /// </summary>
        internal static string SettingsUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site &quot;{0}&quot; could not be deleted.
        /// </summary>
        internal static string SiteParamCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("SiteParamCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site with id {0} could not be updated.
        /// </summary>
        internal static string SiteParamCouldNotBeUpdated {
            get {
                return ResourceManager.GetString("SiteParamCouldNotBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site &quot;{0}&quot; deleted successfully.
        /// </summary>
        internal static string SiteParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("SiteParamDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site with id {0} not found.
        /// </summary>
        internal static string SiteParamNotFound {
            get {
                return ResourceManager.GetString("SiteParamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker with id {0} could not be deleted.
        /// </summary>
        internal static string SiteWithIdCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("SiteWithIdCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag deleted successfully.
        /// </summary>
        internal static string TagDeletedSuccessfully {
            get {
                return ResourceManager.GetString("TagDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag &quot;{0}&quot; created successfully.
        /// </summary>
        internal static string TagParamCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TagParamCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template tags was updated successfully.
        /// </summary>
        internal static string TemplateTagUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TemplateTagUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit &quot;{0}&quot; OTP request could not be completed.
        /// </summary>
        internal static string UnitParamOTPCouldNotCompleted {
            get {
                return ResourceManager.GetString("UnitParamOTPCouldNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect.
        /// </summary>
        internal static string UserNameOrPasswordIncorrect {
            get {
                return ResourceManager.GetString("UserNameOrPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} not found.
        /// </summary>
        internal static string UserNotFoundUserName {
            get {
                return ResourceManager.GetString("UserNotFoundUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} was deleted.
        /// </summary>
        internal static string UserParamWasDeleted {
            get {
                return ResourceManager.GetString("UserParamWasDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} already exist.
        /// </summary>
        internal static string UserUserNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserUserNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} was created.
        /// </summary>
        internal static string UserUserNameWasCreated {
            get {
                return ResourceManager.GetString("UserUserNameWasCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} was updated.
        /// </summary>
        internal static string UserUserNameWasUpdated {
            get {
                return ResourceManager.GetString("UserUserNameWasUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker &quot;{0 {1}&quot; can&apos;t be deleted.
        /// </summary>
        internal static string WorkerParamCantBeDeted {
            get {
                return ResourceManager.GetString("WorkerParamCantBeDeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker with id {0} can&apos;t be updated.
        /// </summary>
        internal static string WorkerParamCantBeUpdated {
            get {
                return ResourceManager.GetString("WorkerParamCantBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker &quot;{0} {1}&quot; deleted successfully.
        /// </summary>
        internal static string WorkerParamDeletedSuccessfully {
            get {
                return ResourceManager.GetString("WorkerParamDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker with id {0} was updated.
        /// </summary>
        internal static string WorkerParamWasUpdated {
            get {
                return ResourceManager.GetString("WorkerParamWasUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker was successfully created.
        /// </summary>
        internal static string WorkerWasSuccessfullyCreated {
            get {
                return ResourceManager.GetString("WorkerWasSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to buy more licenses for additional units to be added..
        /// </summary>
        internal static string YouNeedToBuyMoreLicenses {
            get {
                return ResourceManager.GetString("YouNeedToBuyMoreLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email: {0}. Password has been reset..
        /// </summary>
        internal static string YourEmailPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("YourEmailPasswordHasBeenReset", resourceCulture);
            }
        }
    }
}
