export default {
  xmlTest1: {
    text: '<?xml version="1.0" encoding="UTF-8"?>\n' +
    '<Main>\n' +
    '  <Id>75933</Id>\n' +
    '  <Repeated>0</Repeated>\n' +
    '  <Label>TESTER alle felter</Label>\n' +
    '  <StartDate>2017-11-22</StartDate>\n' +
    '  <EndDate>2027-11-22</EndDate>\n' +
    '  <Language>da</Language>\n' +
    '  <MultiApproval>false</MultiApproval>\n' +
    '  <FastNavigation>false</FastNavigation>\n' +
    '  <Review>false</Review>\n' +
    '  <Summary>false</Summary>\n' +
    '  <DisplayOrder>0</DisplayOrder>\n' +
    '  <ElementList>\n' +
    '    <Element type="DataElement">\n' +
    '      <Id>75933</Id>\n' +
    '      <Label>TESTER alle felter</Label>\n' +
    '      <Description><![CDATA[]]></Description>\n' +
    '      <DisplayOrder>0</DisplayOrder>\n' +
    '      <ReviewEnabled>false</ReviewEnabled>\n' +
    '      <ManualSync>false</ManualSync>\n' +
    '      <ExtraFieldsEnabled>false</ExtraFieldsEnabled>\n' +
    '      <DoneButtonDisabled>true</DoneButtonDisabled>\n' +
    '      <ApprovalEnabled>false</ApprovalEnabled>\n' +
    '      <DataItemGroupList>\n' +
    '        <DataItemGroup type="FieldGroup">\n' +
    '          <Id>213388</Id>\n' +
    '          <Label>GroupOpenClose</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>5</DisplayOrder>\n' +
    '          <Value>Closed</Value>\n' +
    '          <Color>ffe4e4</Color>\n' +
    '          <DataItemList>\n' +
    '            <DataItem type="CheckBox">\n' +
    '              <Id>213393</Id>\n' +
    '              <Label>Checkbox</Label>\n' +
    '              <Description><![CDATA[]]></Description>\n' +
    '              <DisplayOrder>0</DisplayOrder>\n' +
    '              <Selected>false</Selected>\n' +
    '              <Mandatory>false</Mandatory>\n' +
    '              <Color>e7e7e7</Color>\n' +
    '            </DataItem>\n' +
    '          </DataItemList>\n' +
    '        </DataItemGroup>\n' +
    '      </DataItemGroupList>\n' +
    '      <DataItemList>\n' +
    '        <DataItem type="None">\n' +
    '          <Id>213363</Id>\n' +
    '          <Label>Infobox</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>0</DisplayOrder>\n' +
    '          <Color>e8eaf6</Color>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="Timer">\n' +
    '          <Id>213368</Id>\n' +
    '          <Label>TimerStartStop</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>1</DisplayOrder>\n' +
    '          <StopOnSave>false</StopOnSave>\n' +
    '          <Mandatory>false</Mandatory>\n' +
    '          <Color>e2f4fb</Color>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="CheckBox">\n' +
    '          <Id>213373</Id>\n' +
    '          <Label>Checkbox</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>2</DisplayOrder>\n' +
    '          <Selected>false</Selected>\n' +
    '          <Mandatory>false</Mandatory>\n' +
    '          <Color>f5eafa</Color>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="MultiSelect">\n' +
    '          <Id>213378</Id>\n' +
    '          <Label>CheckboxList</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>3</DisplayOrder>\n' +
    '          <Mandatory>false</Mandatory>\n' +
    '          <KeyValuePairList>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>1</Key>\n' +
    '              <Value><![CDATA[A]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>1</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>2</Key>\n' +
    '              <Value><![CDATA[B]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>2</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>3</Key>\n' +
    '              <Value><![CDATA[C]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>3</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>4</Key>\n' +
    '              <Value><![CDATA[D]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>4</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>5</Key>\n' +
    '              <Value><![CDATA[E]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>5</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>6</Key>\n' +
    '              <Value><![CDATA[F]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>6</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '          </KeyValuePairList>\n' +
    '          <Color>f0f8db</Color>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="Date">\n' +
    '          <Id>213383</Id>\n' +
    '          <Label>Date</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>4</DisplayOrder>\n' +
    '          <MinValue>2017-12-06</MinValue>\n' +
    '          <MaxValue>2027-12-06</MaxValue>\n' +
    '          <Value/>\n' +
    '          <Mandatory>false</Mandatory>\n' +
    '          <ReadOnly>false</ReadOnly>\n' +
    '          <Color>fff6df</Color>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="SingleSelect">\n' +
    '          <Id>213398</Id>\n' +
    '          <Label>List</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>6</DisplayOrder>\n' +
    '          <Mandatory>false</Mandatory>\n' +
    '          <KeyValuePairList>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>1</Key>\n' +
    '              <Value><![CDATA[1]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>1</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>2</Key>\n' +
    '              <Value><![CDATA[2]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>2</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>3</Key>\n' +
    '              <Value><![CDATA[3]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>3</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>4</Key>\n' +
    '              <Value><![CDATA[4]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>4</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>5</Key>\n' +
    '              <Value><![CDATA[5]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>5</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '            <KeyValuePair>\n' +
    '              <Key>6</Key>\n' +
    '              <Value><![CDATA[6]]></Value>\n' +
    '              <Selected>false</Selected>\n' +
    '              <DisplayOrder>6</DisplayOrder>\n' +
    '            </KeyValuePair>\n' +
    '          </KeyValuePairList>\n' +
    '          <Color>e8eaf6</Color>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="Number">\n' +
    '          <Id>213403</Id>\n' +
    '          <Label>Number</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>7</DisplayOrder>\n' +
    '          <Mandatory>false</Mandatory>\n' +
    '          <MinValue/>\n' +
    '          <MaxValue/>\n' +
    '          <Value/>\n' +
    '          <DecimalCount/>\n' +
    '          <UnitName/>\n' +
    '          <Color>e2f4fb</Color>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="ShowPDF">\n' +
    '          <Id>213408</Id>\n' +
    '          <Label>PDF</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>8</DisplayOrder>\n' +
    '          <Color>f5eafa</Color>\n' +
    '          <Value>https://eform.microting.com/app_files/uploads/20171122094343_14258_42ce9bafbabd9c255e1b45acfb203203.pdf</Value>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="Comment">\n' +
    '          <Id>213418</Id>\n' +
    '          <Label>TextMultiLine</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>10</DisplayOrder>\n' +
    '          <Multi>1</Multi>\n' +
    '          <GeolocationEnabled>false</GeolocationEnabled>\n' +
    '          <Split>false</Split>\n' +
    '          <Value/>\n' +
    '          <ReadOnly>false</ReadOnly>\n' +
    '          <Mandatory>false</Mandatory>\n' +
    '          <Color>f0f8db</Color>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="Text">\n' +
    '          <Id>213423</Id>\n' +
    '          <Label>TextSingleLine</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>11</DisplayOrder>\n' +
    '          <Multi>0</Multi>\n' +
    '          <GeolocationEnabled>false</GeolocationEnabled>\n' +
    '          <Split>false</Split>\n' +
    '          <Value/>\n' +
    '          <ReadOnly>false</ReadOnly>\n' +
    '          <Mandatory>false</Mandatory>\n' +
    '          <Color>fff6df</Color>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="Picture">\n' +
    '          <Id>213428</Id>\n' +
    '          <Label>Picture</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>12</DisplayOrder>\n' +
    '          <Mandatory>false</Mandatory>\n' +
    '          <Color>ffe4e4</Color>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="Signature">\n' +
    '          <Id>213433</Id>\n' +
    '          <Label>Signature</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>13</DisplayOrder>\n' +
    '          <Mandatory>false</Mandatory>\n' +
    '          <Color>e7e7e7</Color>\n' +
    '        </DataItem>\n' +
    '        <DataItem type="SaveButton">\n' +
    '          <Id>213438</Id>\n' +
    '          <Label>SaveButton</Label>\n' +
    '          <Description><![CDATA[]]></Description>\n' +
    '          <DisplayOrder>14</DisplayOrder>\n' +
    '          <Value/>\n' +
    '          <Color>e8eaf6</Color>\n' +
    '        </DataItem>\n' +
    '      </DataItemList>\n' +
    '    </Element>\n' +
    '  </ElementList>\n' +
    '</Main>'
  }
};
