export enum CustomerPnFieldsEnum {
  Id = 1,
  CreatedBy,
  CustomerNo,
  CompanyName,
  CompanyAddress,
  ZipCode,
  CityName,
  Phone,
  Email,
  ContactPerson,
  Description,
  CreatedDate,
  CompanyAddress2,
  EanCode,
  VatNumber,
  CountryCode,
  CrmId,
  CadastralNumber,
  PropertyNumber,
  ApartmentNumber,
  CompletionYear,
  FloorsWithLivingSpace
}
