//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customers.Pn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomersPnResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomersPnResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Customers.Pn.Properties.CustomersPnResources", typeof(CustomersPnResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer has been created.
        /// </summary>
        internal static string CustomerCreated {
            get {
                return ResourceManager.GetString("CustomerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer deleted successfully.
        /// </summary>
        internal static string CustomerDeletedSuccessfully {
            get {
                return ResourceManager.GetString("CustomerDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        internal static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer updated successfully.
        /// </summary>
        internal static string CustomerUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("CustomerUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while obtaining customer info.
        /// </summary>
        internal static string ErrorObtainingCustomersInfo {
            get {
                return ResourceManager.GetString("ErrorObtainingCustomersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating customer.
        /// </summary>
        internal static string ErrorWhileCreatingCustomer {
            get {
                return ResourceManager.GetString("ErrorWhileCreatingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting customer.
        /// </summary>
        internal static string ErrorWhileDeletingCustomer {
            get {
                return ResourceManager.GetString("ErrorWhileDeletingCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while obtaining fields info.
        /// </summary>
        internal static string ErrorWhileObtainingFieldsInfo {
            get {
                return ResourceManager.GetString("ErrorWhileObtainingFieldsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating customer info.
        /// </summary>
        internal static string ErrorWhileUpdatingCustomerInfo {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while updating fields.
        /// </summary>
        internal static string ErrorWhileUpdatingFields {
            get {
                return ResourceManager.GetString("ErrorWhileUpdatingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields updated successfully.
        /// </summary>
        internal static string FieldsUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("FieldsUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
