export const EformPermissionsNamesSwap = [
  { originalName: 'cases_read', swappedName: 'casesRead' },
  { originalName: 'case_read', swappedName: 'caseRead' },
  { originalName: 'case_update', swappedName: 'caseUpdate' },
  { originalName: 'case_delete', swappedName: 'caseDelete' },
  { originalName: 'case_get_pdf', swappedName: 'caseGetPdf' },
  { originalName: 'case_get_docx', swappedName: 'caseGetDocx' },
  { originalName: 'case_get_pptx', swappedName: 'caseGetPptx' },
  { originalName: 'eforms_create', swappedName: 'eFormsCreate' },
  { originalName: 'eforms_delete', swappedName: 'eFormsDelete' },
  { originalName: 'eforms_read', swappedName: 'eFormsRead' },
  { originalName: 'eforms_update_columns', swappedName: 'eFormsUpdateColumns' },
  { originalName: 'eforms_download_xml', swappedName: 'eFormsDownloadXml' },
  { originalName: 'eforms_upload_zip', swappedName: 'eFormsUploadZip' },
  { originalName: 'eforms_pairing_update', swappedName: 'eformsPairingUpdate' },
  {
    originalName: 'eforms_read_jasper_report',
    swappedName: 'eFormsReadJasperReport',
  },
  {
    originalName: 'eforms_update_jasper_report',
    swappedName: 'eFormsUpdateJasperReport',
  },
  { originalName: 'eforms_update_tags', swappedName: 'eformsUpdateTags' },
  { originalName: 'eforms_pairing_read', swappedName: 'eformsPairingRead' },
  { originalName: 'eforms_read_tags', swappedName: 'eformsReadTags' },
  { originalName: 'eforms_get_csv', swappedName: 'eformsGetCsv' },
  { originalName: 'eforms_get_csv', swappedName: 'eformsGetCsv' },
  { originalName: 'eform_export_eform_excel', swappedName: 'eformExportEformExcel' },
  {
    originalName: 'eform_allow_managing-eform_tags',
    swappedName: 'eformAllowManagingEformTags',
  },
];
